
set -g default-shell "fish"
set -g default-command "fish"

set-option -g xterm-keys on
set-option -g default-terminal xterm-256color
set -g terminal-overrides 'xterm:colors=256'

set-option -g escape-time 0

unbind C-b
set -g prefix C-p
bind C-p send-prefix
bind C-[ previous-window
bind C-] next-window

bind - split-window -v
bind | split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set-option -g history-limit 65536

set-option -g mouse on

set-option -g status-position top
set-option -g status-interval 1
set-option -g status-right "[ %m/%d %H:%M:%S ]"
set-option -g status-bg "colour135"
# set-window-option -g window-status-current-format "#[fg=colour0,bg=colour40,bold] #I:#W #[default]"
set-window-option -g window-status-current-format "#[fg=colour0,bg=colour40,bold] #I:#W #[default]"
set -g pane-border-format "#P: #(ps -f --no-headers --pid #{pane_pid} -o args
)"
