
set -gx ANSIBLE_HOME "$HOME/.ansible"

set -gx ANSIBLE_DEVEL_WARNING 'False'
set -gx ANSIBLE_DIFF_ALWAYS 'True'
set -gx ANSIBLE_MAX_DIFF_SIZE 4096
set -gx ANSIBLE_DEPRECATION_WARNINGS 'False'
set -gx ANSIBLE_NO_TARGET_SYSLOG 'True'
set -gx ANSIBLE_POLL_INTERVAL '5'
set -gx ANSIBLE_EDITOR 'nvim'
set -gx ANSIBLE_HOST_PATTERN_MISMATCH 'error'
set -gx ANSIBLE_INVENTORY_ANY_UNPARSED_IS_FAILED 'True'
set -gx ANSIBLE_LOCALHOST_WARNING 'False'
set -gx ANSIBLE_NOCOWS 'True'
set -gx ANSIBLE_ANY_ERRORS_FATAL 'True'
set -gx ANSIBLE_FORKS '300'
set -gx ANSIBLE_GATHERING 'implicit'
set -gx ANSIBLE_TIMEOUT '15'
set -gx ANSIBLE_INVENTORY_UNPARSED_WARNING 'False'
set -gx ANSIBLE_PERSISTENT_CONNECT_TIMEOUT '10'
set -gx ANSIBLE_PERSISTENT_CONNECT_RETRY_TIMEOUT '5'
set -gx ANSIBLE_LOAD_CALLBACK_PLUGINS 'True'
set -gx ANSIBLE_PYTHON_INTERPRETER 'auto_silent'
set -gx ANSIBLE_TASK_ATTRIBUTE_FAILED 'False'
set -gx ANSIBLE_COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH 'error'
set -gx ANSIBLE_TASK_TIMEOUT 0
set -gx ANSIBLE_VERBOSE_TO_STDERR 'True'
if command -sq bat
  set -gx ANSIBLE_PAGER 'bat'
end

if command -sq launchctl
  # We are likely running on macOS
  set -gx OBJC_DISABLE_INITIALIZE_FORK_SAFETY 'YES'
end

