
version: "1"
color_labels: enabled
git_protocol: ssh
editor: nvim
prompt: enabled
prefer_editor_prompt: disabled
accessible_colors: enabled
accessible_prompter: enabled
pager: bat
aliases:
    co: pr checkout
browser:
