#!perl

# /opt/homebrew/bin/perl

$pdf_mode    = 3;
$latex       = 'uplatex -shell-escape -interaction=nonstopmode -synctex=1 %O %S';
$dvipdf      = 'dvipdfmx %O -o %D %S';
$bibtex      = 'pbibtex %O %B';
$makeindex   = 'mendex %O -o %D %S';
$max_repeat  = 10;
$max_repeat  = 10;
$view        = 'none';
$pvc_view_file_via_temporary = 0;
#$pdf_previewer = "open";
#$pdf_previewer = "open -ga Skim";

